# trunk-ignore-all(checkov/CKV_DOCKER_2)
# trunk-ignore-all(checkov/CKV_DOCKER_3)
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o pipeline ./cmd/market-pipeline

# trunk-ignore(hadolint/DL3007)
# trunk-ignore(checkov/CKV_DOCKER_7)
FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/
COPY --from=builder /app/pipeline .
EXPOSE 8080
CMD ["./pipeline"]